var annotated_dup =
[
    [ "Jeremiah", null, [
      [ "DX12CommandQueue", "class_jeremiah_1_1_d_x12_command_queue.html", "class_jeremiah_1_1_d_x12_command_queue" ],
      [ "EventArgs", "class_jeremiah_1_1_event_args.html", "class_jeremiah_1_1_event_args" ],
      [ "Game", "class_jeremiah_1_1_game.html", "class_jeremiah_1_1_game" ],
      [ "HighResolutionClock", "class_jeremiah_1_1_high_resolution_clock.html", "class_jeremiah_1_1_high_resolution_clock" ],
      [ "KeyEventArgs", "class_jeremiah_1_1_key_event_args.html", "class_jeremiah_1_1_key_event_args" ],
      [ "MouseButtonEventArgs", "class_jeremiah_1_1_mouse_button_event_args.html", "class_jeremiah_1_1_mouse_button_event_args" ],
      [ "MouseMotionEventArgs", "class_jeremiah_1_1_mouse_motion_event_args.html", "class_jeremiah_1_1_mouse_motion_event_args" ],
      [ "MouseWheelEventArgs", "class_jeremiah_1_1_mouse_wheel_event_args.html", "class_jeremiah_1_1_mouse_wheel_event_args" ],
      [ "RenderEventArgs", "class_jeremiah_1_1_render_event_args.html", "class_jeremiah_1_1_render_event_args" ],
      [ "ResizeEventArgs", "class_jeremiah_1_1_resize_event_args.html", "class_jeremiah_1_1_resize_event_args" ],
      [ "UpdateEventArgs", "class_jeremiah_1_1_update_event_args.html", "class_jeremiah_1_1_update_event_args" ],
      [ "UserEventArgs", "class_jeremiah_1_1_user_event_args.html", "class_jeremiah_1_1_user_event_args" ],
      [ "Window", "class_jeremiah_1_1_window.html", "class_jeremiah_1_1_window" ]
    ] ],
    [ "Twl", null, [
      [ "AiController", "class_twl_1_1_ai_controller.html", "class_twl_1_1_ai_controller" ],
      [ "AIControllerComponent", "struct_twl_1_1_a_i_controller_component.html", "struct_twl_1_1_a_i_controller_component" ],
      [ "AIControllerSystem", "class_twl_1_1_a_i_controller_system.html", "class_twl_1_1_a_i_controller_system" ],
      [ "Behaviour", "class_twl_1_1_behaviour.html", "class_twl_1_1_behaviour" ],
      [ "CharacterController", "class_twl_1_1_character_controller.html", "class_twl_1_1_character_controller" ],
      [ "CharacterControllerComponent", "struct_twl_1_1_character_controller_component.html", "struct_twl_1_1_character_controller_component" ],
      [ "CharacterControllerSystem", "class_twl_1_1_character_controller_system.html", "class_twl_1_1_character_controller_system" ],
      [ "Chunk", "struct_twl_1_1_chunk.html", "struct_twl_1_1_chunk" ],
      [ "Core", "class_twl_1_1_core.html", "class_twl_1_1_core" ],
      [ "DX12DeviceFactory", "class_twl_1_1_d_x12_device_factory.html", null ],
      [ "DX12GpuResourceManager", "class_twl_1_1_d_x12_gpu_resource_manager.html", "class_twl_1_1_d_x12_gpu_resource_manager" ],
      [ "DX12Renderer", "class_twl_1_1_d_x12_renderer.html", "class_twl_1_1_d_x12_renderer" ],
      [ "DX12Sprite", "class_twl_1_1_d_x12_sprite.html", "class_twl_1_1_d_x12_sprite" ],
      [ "DX12Texture", "class_twl_1_1_d_x12_texture.html", "class_twl_1_1_d_x12_texture" ],
      [ "Entity", "class_twl_1_1_entity.html", "class_twl_1_1_entity" ],
      [ "Grid", "class_twl_1_1_grid.html", "class_twl_1_1_grid" ],
      [ "InputManager", "class_twl_1_1_input_manager.html", "class_twl_1_1_input_manager" ],
      [ "Joystick", "class_twl_1_1_joystick.html", "class_twl_1_1_joystick" ],
      [ "Level", "class_twl_1_1_level.html", "class_twl_1_1_level" ],
      [ "LevelBuilder", "class_twl_1_1_level_builder.html", "class_twl_1_1_level_builder" ],
      [ "LevelElement", "struct_twl_1_1_level_element.html", "struct_twl_1_1_level_element" ],
      [ "LevelReader", "class_twl_1_1_level_reader.html", "class_twl_1_1_level_reader" ],
      [ "MouseState", "struct_twl_1_1_mouse_state.html", "struct_twl_1_1_mouse_state" ],
      [ "OrthographicCamera", "class_twl_1_1_orthographic_camera.html", "class_twl_1_1_orthographic_camera" ],
      [ "ProjectileComponent", "struct_twl_1_1_projectile_component.html", "struct_twl_1_1_projectile_component" ],
      [ "ProjectileSystem", "class_twl_1_1_projectile_system.html", "class_twl_1_1_projectile_system" ],
      [ "RenderImGui", "class_twl_1_1_render_im_gui.html", "class_twl_1_1_render_im_gui" ],
      [ "RenderSFML", "class_twl_1_1_render_s_f_m_l.html", "class_twl_1_1_render_s_f_m_l" ],
      [ "Resource", "class_twl_1_1_resource.html", "class_twl_1_1_resource" ],
      [ "ResourceManager", "class_twl_1_1_resource_manager.html", "class_twl_1_1_resource_manager" ],
      [ "RomMount", "class_twl_1_1_rom_mount.html", "class_twl_1_1_rom_mount" ],
      [ "SceneMaganger", "class_twl_1_1_scene_maganger.html", "class_twl_1_1_scene_maganger" ],
      [ "Sprite", "class_twl_1_1_sprite.html", "class_twl_1_1_sprite" ],
      [ "SpriteComponent", "struct_twl_1_1_sprite_component.html", "struct_twl_1_1_sprite_component" ],
      [ "SpriteRenderer", "class_twl_1_1_sprite_renderer.html", "class_twl_1_1_sprite_renderer" ],
      [ "SwitchInput", "class_twl_1_1_switch_input.html", "class_twl_1_1_switch_input" ],
      [ "Tileset", "struct_twl_1_1_tileset.html", "struct_twl_1_1_tileset" ],
      [ "TransformComponent", "struct_twl_1_1_transform_component.html", "struct_twl_1_1_transform_component" ],
      [ "TransformSystem", "class_twl_1_1_transform_system.html", "class_twl_1_1_transform_system" ],
      [ "WhiteBoard", "class_twl_1_1_white_board.html", "class_twl_1_1_white_board" ],
      [ "WindowsInput", "class_twl_1_1_windows_input.html", "class_twl_1_1_windows_input" ]
    ] ]
];